const root = @import("root.zig");
pub const NodeKind = root.pb.Node._node_case;

pub const NodeRef = union(NodeKind) {
    alias: *const root.pb.Alias,
    range_var: *const root.pb.RangeVar,
    table_func: *const root.pb.TableFunc,
    into_clause: *const root.pb.IntoClause,
    @"var": *const root.pb.Var,
    param: *const root.pb.Param,
    aggref: *const root.pb.Aggref,
    grouping_func: *const root.pb.GroupingFunc,
    window_func: *const root.pb.WindowFunc,
    window_func_run_condition: *const root.pb.WindowFuncRunCondition,
    merge_support_func: *const root.pb.MergeSupportFunc,
    subscripting_ref: *const root.pb.SubscriptingRef,
    func_expr: *const root.pb.FuncExpr,
    named_arg_expr: *const root.pb.NamedArgExpr,
    op_expr: *const root.pb.OpExpr,
    distinct_expr: *const root.pb.DistinctExpr,
    null_if_expr: *const root.pb.NullIfExpr,
    scalar_array_op_expr: *const root.pb.ScalarArrayOpExpr,
    bool_expr: *const root.pb.BoolExpr,
    sub_link: *const root.pb.SubLink,
    sub_plan: *const root.pb.SubPlan,
    alternative_sub_plan: *const root.pb.AlternativeSubPlan,
    field_select: *const root.pb.FieldSelect,
    field_store: *const root.pb.FieldStore,
    relabel_type: *const root.pb.RelabelType,
    coerce_via_io: *const root.pb.CoerceViaIO,
    array_coerce_expr: *const root.pb.ArrayCoerceExpr,
    convert_rowtype_expr: *const root.pb.ConvertRowtypeExpr,
    collate_expr: *const root.pb.CollateExpr,
    case_expr: *const root.pb.CaseExpr,
    case_when: *const root.pb.CaseWhen,
    case_test_expr: *const root.pb.CaseTestExpr,
    array_expr: *const root.pb.ArrayExpr,
    row_expr: *const root.pb.RowExpr,
    row_compare_expr: *const root.pb.RowCompareExpr,
    coalesce_expr: *const root.pb.CoalesceExpr,
    min_max_expr: *const root.pb.MinMaxExpr,
    sqlvalue_function: *const root.pb.SQLValueFunction,
    xml_expr: *const root.pb.XmlExpr,
    json_format: *const root.pb.JsonFormat,
    json_returning: *const root.pb.JsonReturning,
    json_value_expr: *const root.pb.JsonValueExpr,
    json_constructor_expr: *const root.pb.JsonConstructorExpr,
    json_is_predicate: *const root.pb.JsonIsPredicate,
    json_behavior: *const root.pb.JsonBehavior,
    json_expr: *const root.pb.JsonExpr,
    json_table_path: *const root.pb.JsonTablePath,
    json_table_path_scan: *const root.pb.JsonTablePathScan,
    json_table_sibling_join: *const root.pb.JsonTableSiblingJoin,
    null_test: *const root.pb.NullTest,
    boolean_test: *const root.pb.BooleanTest,
    merge_action: *const root.pb.MergeAction,
    coerce_to_domain: *const root.pb.CoerceToDomain,
    coerce_to_domain_value: *const root.pb.CoerceToDomainValue,
    set_to_default: *const root.pb.SetToDefault,
    current_of_expr: *const root.pb.CurrentOfExpr,
    next_value_expr: *const root.pb.NextValueExpr,
    inference_elem: *const root.pb.InferenceElem,
    target_entry: *const root.pb.TargetEntry,
    range_tbl_ref: *const root.pb.RangeTblRef,
    join_expr: *const root.pb.JoinExpr,
    from_expr: *const root.pb.FromExpr,
    on_conflict_expr: *const root.pb.OnConflictExpr,
    query: *const root.pb.Query,
    type_name: *const root.pb.TypeName,
    column_ref: *const root.pb.ColumnRef,
    param_ref: *const root.pb.ParamRef,
    a_expr: *const root.pb.A_Expr,
    type_cast: *const root.pb.TypeCast,
    collate_clause: *const root.pb.CollateClause,
    role_spec: *const root.pb.RoleSpec,
    func_call: *const root.pb.FuncCall,
    a_star: *const root.pb.A_Star,
    a_indices: *const root.pb.A_Indices,
    a_indirection: *const root.pb.A_Indirection,
    a_array_expr: *const root.pb.A_ArrayExpr,
    res_target: *const root.pb.ResTarget,
    multi_assign_ref: *const root.pb.MultiAssignRef,
    sort_by: *const root.pb.SortBy,
    window_def: *const root.pb.WindowDef,
    range_subselect: *const root.pb.RangeSubselect,
    range_function: *const root.pb.RangeFunction,
    range_table_func: *const root.pb.RangeTableFunc,
    range_table_func_col: *const root.pb.RangeTableFuncCol,
    range_table_sample: *const root.pb.RangeTableSample,
    column_def: *const root.pb.ColumnDef,
    table_like_clause: *const root.pb.TableLikeClause,
    index_elem: *const root.pb.IndexElem,
    def_elem: *const root.pb.DefElem,
    locking_clause: *const root.pb.LockingClause,
    xml_serialize: *const root.pb.XmlSerialize,
    partition_elem: *const root.pb.PartitionElem,
    partition_spec: *const root.pb.PartitionSpec,
    partition_bound_spec: *const root.pb.PartitionBoundSpec,
    partition_range_datum: *const root.pb.PartitionRangeDatum,
    single_partition_spec: *const root.pb.SinglePartitionSpec,
    partition_cmd: *const root.pb.PartitionCmd,
    range_tbl_entry: *const root.pb.RangeTblEntry,
    rtepermission_info: *const root.pb.RTEPermissionInfo,
    range_tbl_function: *const root.pb.RangeTblFunction,
    table_sample_clause: *const root.pb.TableSampleClause,
    with_check_option: *const root.pb.WithCheckOption,
    sort_group_clause: *const root.pb.SortGroupClause,
    grouping_set: *const root.pb.GroupingSet,
    window_clause: *const root.pb.WindowClause,
    row_mark_clause: *const root.pb.RowMarkClause,
    with_clause: *const root.pb.WithClause,
    infer_clause: *const root.pb.InferClause,
    on_conflict_clause: *const root.pb.OnConflictClause,
    ctesearch_clause: *const root.pb.CTESearchClause,
    ctecycle_clause: *const root.pb.CTECycleClause,
    common_table_expr: *const root.pb.CommonTableExpr,
    merge_when_clause: *const root.pb.MergeWhenClause,
    trigger_transition: *const root.pb.TriggerTransition,
    json_output: *const root.pb.JsonOutput,
    json_argument: *const root.pb.JsonArgument,
    json_func_expr: *const root.pb.JsonFuncExpr,
    json_table_path_spec: *const root.pb.JsonTablePathSpec,
    json_table: *const root.pb.JsonTable,
    json_table_column: *const root.pb.JsonTableColumn,
    json_key_value: *const root.pb.JsonKeyValue,
    json_parse_expr: *const root.pb.JsonParseExpr,
    json_scalar_expr: *const root.pb.JsonScalarExpr,
    json_serialize_expr: *const root.pb.JsonSerializeExpr,
    json_object_constructor: *const root.pb.JsonObjectConstructor,
    json_array_constructor: *const root.pb.JsonArrayConstructor,
    json_array_query_constructor: *const root.pb.JsonArrayQueryConstructor,
    json_agg_constructor: *const root.pb.JsonAggConstructor,
    json_object_agg: *const root.pb.JsonObjectAgg,
    json_array_agg: *const root.pb.JsonArrayAgg,
    raw_stmt: *const root.pb.RawStmt,
    insert_stmt: *const root.pb.InsertStmt,
    delete_stmt: *const root.pb.DeleteStmt,
    update_stmt: *const root.pb.UpdateStmt,
    merge_stmt: *const root.pb.MergeStmt,
    select_stmt: *const root.pb.SelectStmt,
    set_operation_stmt: *const root.pb.SetOperationStmt,
    return_stmt: *const root.pb.ReturnStmt,
    plassign_stmt: *const root.pb.PLAssignStmt,
    create_schema_stmt: *const root.pb.CreateSchemaStmt,
    alter_table_stmt: *const root.pb.AlterTableStmt,
    replica_identity_stmt: *const root.pb.ReplicaIdentityStmt,
    alter_table_cmd: *const root.pb.AlterTableCmd,
    alter_collation_stmt: *const root.pb.AlterCollationStmt,
    alter_domain_stmt: *const root.pb.AlterDomainStmt,
    grant_stmt: *const root.pb.GrantStmt,
    object_with_args: *const root.pb.ObjectWithArgs,
    access_priv: *const root.pb.AccessPriv,
    grant_role_stmt: *const root.pb.GrantRoleStmt,
    alter_default_privileges_stmt: *const root.pb.AlterDefaultPrivilegesStmt,
    copy_stmt: *const root.pb.CopyStmt,
    variable_set_stmt: *const root.pb.VariableSetStmt,
    variable_show_stmt: *const root.pb.VariableShowStmt,
    create_stmt: *const root.pb.CreateStmt,
    constraint: *const root.pb.Constraint,
    create_table_space_stmt: *const root.pb.CreateTableSpaceStmt,
    drop_table_space_stmt: *const root.pb.DropTableSpaceStmt,
    alter_table_space_options_stmt: *const root.pb.AlterTableSpaceOptionsStmt,
    alter_table_move_all_stmt: *const root.pb.AlterTableMoveAllStmt,
    create_extension_stmt: *const root.pb.CreateExtensionStmt,
    alter_extension_stmt: *const root.pb.AlterExtensionStmt,
    alter_extension_contents_stmt: *const root.pb.AlterExtensionContentsStmt,
    create_fdw_stmt: *const root.pb.CreateFdwStmt,
    alter_fdw_stmt: *const root.pb.AlterFdwStmt,
    create_foreign_server_stmt: *const root.pb.CreateForeignServerStmt,
    alter_foreign_server_stmt: *const root.pb.AlterForeignServerStmt,
    create_foreign_table_stmt: *const root.pb.CreateForeignTableStmt,
    create_user_mapping_stmt: *const root.pb.CreateUserMappingStmt,
    alter_user_mapping_stmt: *const root.pb.AlterUserMappingStmt,
    drop_user_mapping_stmt: *const root.pb.DropUserMappingStmt,
    import_foreign_schema_stmt: *const root.pb.ImportForeignSchemaStmt,
    create_policy_stmt: *const root.pb.CreatePolicyStmt,
    alter_policy_stmt: *const root.pb.AlterPolicyStmt,
    create_am_stmt: *const root.pb.CreateAmStmt,
    create_trig_stmt: *const root.pb.CreateTrigStmt,
    create_event_trig_stmt: *const root.pb.CreateEventTrigStmt,
    alter_event_trig_stmt: *const root.pb.AlterEventTrigStmt,
    create_plang_stmt: *const root.pb.CreatePLangStmt,
    create_role_stmt: *const root.pb.CreateRoleStmt,
    alter_role_stmt: *const root.pb.AlterRoleStmt,
    alter_role_set_stmt: *const root.pb.AlterRoleSetStmt,
    drop_role_stmt: *const root.pb.DropRoleStmt,
    create_seq_stmt: *const root.pb.CreateSeqStmt,
    alter_seq_stmt: *const root.pb.AlterSeqStmt,
    define_stmt: *const root.pb.DefineStmt,
    create_domain_stmt: *const root.pb.CreateDomainStmt,
    create_op_class_stmt: *const root.pb.CreateOpClassStmt,
    create_op_class_item: *const root.pb.CreateOpClassItem,
    create_op_family_stmt: *const root.pb.CreateOpFamilyStmt,
    alter_op_family_stmt: *const root.pb.AlterOpFamilyStmt,
    drop_stmt: *const root.pb.DropStmt,
    truncate_stmt: *const root.pb.TruncateStmt,
    comment_stmt: *const root.pb.CommentStmt,
    sec_label_stmt: *const root.pb.SecLabelStmt,
    declare_cursor_stmt: *const root.pb.DeclareCursorStmt,
    close_portal_stmt: *const root.pb.ClosePortalStmt,
    fetch_stmt: *const root.pb.FetchStmt,
    index_stmt: *const root.pb.IndexStmt,
    create_stats_stmt: *const root.pb.CreateStatsStmt,
    stats_elem: *const root.pb.StatsElem,
    alter_stats_stmt: *const root.pb.AlterStatsStmt,
    create_function_stmt: *const root.pb.CreateFunctionStmt,
    function_parameter: *const root.pb.FunctionParameter,
    alter_function_stmt: *const root.pb.AlterFunctionStmt,
    do_stmt: *const root.pb.DoStmt,
    inline_code_block: *const root.pb.InlineCodeBlock,
    call_stmt: *const root.pb.CallStmt,
    call_context: *const root.pb.CallContext,
    rename_stmt: *const root.pb.RenameStmt,
    alter_object_depends_stmt: *const root.pb.AlterObjectDependsStmt,
    alter_object_schema_stmt: *const root.pb.AlterObjectSchemaStmt,
    alter_owner_stmt: *const root.pb.AlterOwnerStmt,
    alter_operator_stmt: *const root.pb.AlterOperatorStmt,
    alter_type_stmt: *const root.pb.AlterTypeStmt,
    rule_stmt: *const root.pb.RuleStmt,
    notify_stmt: *const root.pb.NotifyStmt,
    listen_stmt: *const root.pb.ListenStmt,
    unlisten_stmt: *const root.pb.UnlistenStmt,
    transaction_stmt: *const root.pb.TransactionStmt,
    composite_type_stmt: *const root.pb.CompositeTypeStmt,
    create_enum_stmt: *const root.pb.CreateEnumStmt,
    create_range_stmt: *const root.pb.CreateRangeStmt,
    alter_enum_stmt: *const root.pb.AlterEnumStmt,
    view_stmt: *const root.pb.ViewStmt,
    load_stmt: *const root.pb.LoadStmt,
    createdb_stmt: *const root.pb.CreatedbStmt,
    alter_database_stmt: *const root.pb.AlterDatabaseStmt,
    alter_database_refresh_coll_stmt: *const root.pb.AlterDatabaseRefreshCollStmt,
    alter_database_set_stmt: *const root.pb.AlterDatabaseSetStmt,
    dropdb_stmt: *const root.pb.DropdbStmt,
    alter_system_stmt: *const root.pb.AlterSystemStmt,
    cluster_stmt: *const root.pb.ClusterStmt,
    vacuum_stmt: *const root.pb.VacuumStmt,
    vacuum_relation: *const root.pb.VacuumRelation,
    explain_stmt: *const root.pb.ExplainStmt,
    create_table_as_stmt: *const root.pb.CreateTableAsStmt,
    refresh_mat_view_stmt: *const root.pb.RefreshMatViewStmt,
    check_point_stmt: *const root.pb.CheckPointStmt,
    discard_stmt: *const root.pb.DiscardStmt,
    lock_stmt: *const root.pb.LockStmt,
    constraints_set_stmt: *const root.pb.ConstraintsSetStmt,
    reindex_stmt: *const root.pb.ReindexStmt,
    create_conversion_stmt: *const root.pb.CreateConversionStmt,
    create_cast_stmt: *const root.pb.CreateCastStmt,
    create_transform_stmt: *const root.pb.CreateTransformStmt,
    prepare_stmt: *const root.pb.PrepareStmt,
    execute_stmt: *const root.pb.ExecuteStmt,
    deallocate_stmt: *const root.pb.DeallocateStmt,
    drop_owned_stmt: *const root.pb.DropOwnedStmt,
    reassign_owned_stmt: *const root.pb.ReassignOwnedStmt,
    alter_tsdictionary_stmt: *const root.pb.AlterTSDictionaryStmt,
    alter_tsconfiguration_stmt: *const root.pb.AlterTSConfigurationStmt,
    publication_table: *const root.pb.PublicationTable,
    publication_obj_spec: *const root.pb.PublicationObjSpec,
    create_publication_stmt: *const root.pb.CreatePublicationStmt,
    alter_publication_stmt: *const root.pb.AlterPublicationStmt,
    create_subscription_stmt: *const root.pb.CreateSubscriptionStmt,
    alter_subscription_stmt: *const root.pb.AlterSubscriptionStmt,
    drop_subscription_stmt: *const root.pb.DropSubscriptionStmt,
    integer: *const root.pb.Integer,
    float: *const root.pb.Float,
    boolean: *const root.pb.Boolean,
    string: *const root.pb.String,
    bit_string: *const root.pb.BitString,
    list: *const root.pb.List,
    int_list: *const root.pb.IntList,
    oid_list: *const root.pb.OidList,
    a_const: *const root.pb.A_Const,

    pub fn toOwnedNode(self: NodeRef) root.pb.Node {
        return .{
            .node = switch (self) {
                inline else => |payload, tag| @unionInit(root.pb.Node.node_union, @tagName(tag), payload.*),
            },
        };
    }

    pub fn deparse(self: NodeRef, allocator: root.Allocator) root.ApiError!root.Outcome(root.OwnedString) {
        if (try statementFallback(self, allocator)) |result| return .{ .ok = result };
        var node = self.toOwnedNode();
        var parse_result = root.pb.ParseResult{ .version = root.pg_version_num };
        try parse_result.stmts.append(allocator, .{ .stmt = &node });
        defer parse_result.stmts.deinit(allocator);
        return root.ops.deparseGeneratedParseResult(allocator, &parse_result);
    }

    pub fn deparseDirect(self: NodeRef, allocator: root.Allocator) root.ApiError!root.Outcome(root.OwnedString) {
        if (try statementFallback(self, allocator)) |result| return .{ .ok = result };
        var node = self.toOwnedNode();
        var parse_result = root.pb.ParseResult{ .version = root.pg_version_num };
        try parse_result.stmts.append(allocator, .{ .stmt = &node });
        defer parse_result.stmts.deinit(allocator);
        return root.ops.deparseGeneratedParseResult(allocator, &parse_result);
    }
};

pub fn toRef(node: *const root.pb.Node) ?NodeRef {
    if (@intFromPtr(node) == 0) return null;
    const tagged = node.node orelse return null;
    return switch (tagged) {
        inline else => |*payload, tag| @unionInit(NodeRef, @tagName(tag), payload),
    };
}

pub fn fromKindPtr(kind: NodeKind, ptr: *const anyopaque) ?NodeRef {
    if (@intFromPtr(ptr) == 0) return null;

    inline for (@typeInfo(NodeRef).@"union".fields) |field| {
        if (@field(NodeKind, field.name) == kind) {
            return @unionInit(NodeRef, field.name, @as(field.type, @ptrCast(@alignCast(ptr))));
        }
    }

    return null;
}

fn statementFallback(self: NodeRef, allocator: root.Allocator) root.Allocator.Error!?root.OwnedString {
    const sql = switch (self) {
        .select_stmt => "SELECT",
        .insert_stmt => "INSERT",
        .update_stmt => "UPDATE",
        .delete_stmt => "DELETE",
        .merge_stmt => "MERGE",
        else => return null,
    };

    return .{
        .allocator = allocator,
        .value = try allocator.dupe(u8, sql),
    };
}
