const root = @import("root.zig");
const c = root.c;

pub const Context = enum {
    none,
    select,
    dml,
    ddl,
    call,
};

pub const NodeRef = union(enum) {
    AArrayExpr: *const c.PgQuery__AArrayExpr,
    AConst: *const c.PgQuery__AConst,
    AExpr: *const c.PgQuery__AExpr,
    AIndices: *const c.PgQuery__AIndices,
    AIndirection: *const c.PgQuery__AIndirection,
    AStar: *const c.PgQuery__AStar,
    AccessPriv: *const c.PgQuery__AccessPriv,
    Aggref: *const c.PgQuery__Aggref,
    Alias: *const c.PgQuery__Alias,
    AlterCollationStmt: *const c.PgQuery__AlterCollationStmt,
    AlterDatabaseRefreshCollStmt: *const c.PgQuery__AlterDatabaseRefreshCollStmt,
    AlterDatabaseSetStmt: *const c.PgQuery__AlterDatabaseSetStmt,
    AlterDatabaseStmt: *const c.PgQuery__AlterDatabaseStmt,
    AlterDefaultPrivilegesStmt: *const c.PgQuery__AlterDefaultPrivilegesStmt,
    AlterDomainStmt: *const c.PgQuery__AlterDomainStmt,
    AlterEnumStmt: *const c.PgQuery__AlterEnumStmt,
    AlterEventTrigStmt: *const c.PgQuery__AlterEventTrigStmt,
    AlterExtensionContentsStmt: *const c.PgQuery__AlterExtensionContentsStmt,
    AlterExtensionStmt: *const c.PgQuery__AlterExtensionStmt,
    AlterFdwStmt: *const c.PgQuery__AlterFdwStmt,
    AlterForeignServerStmt: *const c.PgQuery__AlterForeignServerStmt,
    AlterFunctionStmt: *const c.PgQuery__AlterFunctionStmt,
    AlterObjectDependsStmt: *const c.PgQuery__AlterObjectDependsStmt,
    AlterObjectSchemaStmt: *const c.PgQuery__AlterObjectSchemaStmt,
    AlterOpFamilyStmt: *const c.PgQuery__AlterOpFamilyStmt,
    AlterOperatorStmt: *const c.PgQuery__AlterOperatorStmt,
    AlterOwnerStmt: *const c.PgQuery__AlterOwnerStmt,
    AlterPolicyStmt: *const c.PgQuery__AlterPolicyStmt,
    AlterPublicationStmt: *const c.PgQuery__AlterPublicationStmt,
    AlterRoleSetStmt: *const c.PgQuery__AlterRoleSetStmt,
    AlterRoleStmt: *const c.PgQuery__AlterRoleStmt,
    AlterSeqStmt: *const c.PgQuery__AlterSeqStmt,
    AlterStatsStmt: *const c.PgQuery__AlterStatsStmt,
    AlterSubscriptionStmt: *const c.PgQuery__AlterSubscriptionStmt,
    AlterSystemStmt: *const c.PgQuery__AlterSystemStmt,
    AlterTableCmd: *const c.PgQuery__AlterTableCmd,
    AlterTableMoveAllStmt: *const c.PgQuery__AlterTableMoveAllStmt,
    AlterTableSpaceOptionsStmt: *const c.PgQuery__AlterTableSpaceOptionsStmt,
    AlterTableStmt: *const c.PgQuery__AlterTableStmt,
    AlterTsconfigurationStmt: *const c.PgQuery__AlterTSConfigurationStmt,
    AlterTsdictionaryStmt: *const c.PgQuery__AlterTSDictionaryStmt,
    AlterTypeStmt: *const c.PgQuery__AlterTypeStmt,
    AlterUserMappingStmt: *const c.PgQuery__AlterUserMappingStmt,
    AlternativeSubPlan: *const c.PgQuery__AlternativeSubPlan,
    ArrayCoerceExpr: *const c.PgQuery__ArrayCoerceExpr,
    ArrayExpr: *const c.PgQuery__ArrayExpr,
    BitString: *const c.PgQuery__BitString,
    BoolExpr: *const c.PgQuery__BoolExpr,
    Boolean: *const c.PgQuery__Boolean,
    BooleanTest: *const c.PgQuery__BooleanTest,
    CallContext: *const c.PgQuery__CallContext,
    CallStmt: *const c.PgQuery__CallStmt,
    CaseExpr: *const c.PgQuery__CaseExpr,
    CaseTestExpr: *const c.PgQuery__CaseTestExpr,
    CaseWhen: *const c.PgQuery__CaseWhen,
    CheckPointStmt: *const c.PgQuery__CheckPointStmt,
    ClosePortalStmt: *const c.PgQuery__ClosePortalStmt,
    ClusterStmt: *const c.PgQuery__ClusterStmt,
    CoalesceExpr: *const c.PgQuery__CoalesceExpr,
    CoerceToDomain: *const c.PgQuery__CoerceToDomain,
    CoerceToDomainValue: *const c.PgQuery__CoerceToDomainValue,
    CoerceViaIo: *const c.PgQuery__CoerceViaIO,
    CollateClause: *const c.PgQuery__CollateClause,
    CollateExpr: *const c.PgQuery__CollateExpr,
    ColumnDef: *const c.PgQuery__ColumnDef,
    ColumnRef: *const c.PgQuery__ColumnRef,
    CommentStmt: *const c.PgQuery__CommentStmt,
    CommonTableExpr: *const c.PgQuery__CommonTableExpr,
    CompositeTypeStmt: *const c.PgQuery__CompositeTypeStmt,
    Constraint: *const c.PgQuery__Constraint,
    ConstraintsSetStmt: *const c.PgQuery__ConstraintsSetStmt,
    ConvertRowtypeExpr: *const c.PgQuery__ConvertRowtypeExpr,
    CopyStmt: *const c.PgQuery__CopyStmt,
    CreateAmStmt: *const c.PgQuery__CreateAmStmt,
    CreateCastStmt: *const c.PgQuery__CreateCastStmt,
    CreateConversionStmt: *const c.PgQuery__CreateConversionStmt,
    CreateDomainStmt: *const c.PgQuery__CreateDomainStmt,
    CreateEnumStmt: *const c.PgQuery__CreateEnumStmt,
    CreateEventTrigStmt: *const c.PgQuery__CreateEventTrigStmt,
    CreateExtensionStmt: *const c.PgQuery__CreateExtensionStmt,
    CreateFdwStmt: *const c.PgQuery__CreateFdwStmt,
    CreateForeignServerStmt: *const c.PgQuery__CreateForeignServerStmt,
    CreateForeignTableStmt: *const c.PgQuery__CreateForeignTableStmt,
    CreateFunctionStmt: *const c.PgQuery__CreateFunctionStmt,
    CreateOpClassItem: *const c.PgQuery__CreateOpClassItem,
    CreateOpClassStmt: *const c.PgQuery__CreateOpClassStmt,
    CreateOpFamilyStmt: *const c.PgQuery__CreateOpFamilyStmt,
    CreatePlangStmt: *const c.PgQuery__CreatePLangStmt,
    CreatePolicyStmt: *const c.PgQuery__CreatePolicyStmt,
    CreatePublicationStmt: *const c.PgQuery__CreatePublicationStmt,
    CreateRangeStmt: *const c.PgQuery__CreateRangeStmt,
    CreateRoleStmt: *const c.PgQuery__CreateRoleStmt,
    CreateSchemaStmt: *const c.PgQuery__CreateSchemaStmt,
    CreateSeqStmt: *const c.PgQuery__CreateSeqStmt,
    CreateStatsStmt: *const c.PgQuery__CreateStatsStmt,
    CreateStmt: *const c.PgQuery__CreateStmt,
    CreateSubscriptionStmt: *const c.PgQuery__CreateSubscriptionStmt,
    CreateTableAsStmt: *const c.PgQuery__CreateTableAsStmt,
    CreateTableSpaceStmt: *const c.PgQuery__CreateTableSpaceStmt,
    CreateTransformStmt: *const c.PgQuery__CreateTransformStmt,
    CreateTrigStmt: *const c.PgQuery__CreateTrigStmt,
    CreateUserMappingStmt: *const c.PgQuery__CreateUserMappingStmt,
    CreatedbStmt: *const c.PgQuery__CreatedbStmt,
    CtecycleClause: *const c.PgQuery__CTECycleClause,
    CtesearchClause: *const c.PgQuery__CTESearchClause,
    CurrentOfExpr: *const c.PgQuery__CurrentOfExpr,
    DeallocateStmt: *const c.PgQuery__DeallocateStmt,
    DeclareCursorStmt: *const c.PgQuery__DeclareCursorStmt,
    DefElem: *const c.PgQuery__DefElem,
    DefineStmt: *const c.PgQuery__DefineStmt,
    DeleteStmt: *const c.PgQuery__DeleteStmt,
    DiscardStmt: *const c.PgQuery__DiscardStmt,
    DistinctExpr: *const c.PgQuery__DistinctExpr,
    DoStmt: *const c.PgQuery__DoStmt,
    DropOwnedStmt: *const c.PgQuery__DropOwnedStmt,
    DropRoleStmt: *const c.PgQuery__DropRoleStmt,
    DropStmt: *const c.PgQuery__DropStmt,
    DropSubscriptionStmt: *const c.PgQuery__DropSubscriptionStmt,
    DropTableSpaceStmt: *const c.PgQuery__DropTableSpaceStmt,
    DropUserMappingStmt: *const c.PgQuery__DropUserMappingStmt,
    DropdbStmt: *const c.PgQuery__DropdbStmt,
    ExecuteStmt: *const c.PgQuery__ExecuteStmt,
    ExplainStmt: *const c.PgQuery__ExplainStmt,
    FetchStmt: *const c.PgQuery__FetchStmt,
    FieldSelect: *const c.PgQuery__FieldSelect,
    FieldStore: *const c.PgQuery__FieldStore,
    Float: *const c.PgQuery__Float,
    FromExpr: *const c.PgQuery__FromExpr,
    FuncCall: *const c.PgQuery__FuncCall,
    FuncExpr: *const c.PgQuery__FuncExpr,
    FunctionParameter: *const c.PgQuery__FunctionParameter,
    GrantRoleStmt: *const c.PgQuery__GrantRoleStmt,
    GrantStmt: *const c.PgQuery__GrantStmt,
    GroupingFunc: *const c.PgQuery__GroupingFunc,
    GroupingSet: *const c.PgQuery__GroupingSet,
    ImportForeignSchemaStmt: *const c.PgQuery__ImportForeignSchemaStmt,
    IndexElem: *const c.PgQuery__IndexElem,
    IndexStmt: *const c.PgQuery__IndexStmt,
    InferClause: *const c.PgQuery__InferClause,
    InferenceElem: *const c.PgQuery__InferenceElem,
    InlineCodeBlock: *const c.PgQuery__InlineCodeBlock,
    InsertStmt: *const c.PgQuery__InsertStmt,
    IntList: *const c.PgQuery__IntList,
    Integer: *const c.PgQuery__Integer,
    IntoClause: *const c.PgQuery__IntoClause,
    JoinExpr: *const c.PgQuery__JoinExpr,
    JsonAggConstructor: *const c.PgQuery__JsonAggConstructor,
    JsonArgument: *const c.PgQuery__JsonArgument,
    JsonArrayAgg: *const c.PgQuery__JsonArrayAgg,
    JsonArrayConstructor: *const c.PgQuery__JsonArrayConstructor,
    JsonArrayQueryConstructor: *const c.PgQuery__JsonArrayQueryConstructor,
    JsonBehavior: *const c.PgQuery__JsonBehavior,
    JsonConstructorExpr: *const c.PgQuery__JsonConstructorExpr,
    JsonExpr: *const c.PgQuery__JsonExpr,
    JsonFormat: *const c.PgQuery__JsonFormat,
    JsonFuncExpr: *const c.PgQuery__JsonFuncExpr,
    JsonIsPredicate: *const c.PgQuery__JsonIsPredicate,
    JsonKeyValue: *const c.PgQuery__JsonKeyValue,
    JsonObjectAgg: *const c.PgQuery__JsonObjectAgg,
    JsonObjectConstructor: *const c.PgQuery__JsonObjectConstructor,
    JsonOutput: *const c.PgQuery__JsonOutput,
    JsonParseExpr: *const c.PgQuery__JsonParseExpr,
    JsonReturning: *const c.PgQuery__JsonReturning,
    JsonScalarExpr: *const c.PgQuery__JsonScalarExpr,
    JsonSerializeExpr: *const c.PgQuery__JsonSerializeExpr,
    JsonTable: *const c.PgQuery__JsonTable,
    JsonTableColumn: *const c.PgQuery__JsonTableColumn,
    JsonTablePath: *const c.PgQuery__JsonTablePath,
    JsonTablePathScan: *const c.PgQuery__JsonTablePathScan,
    JsonTablePathSpec: *const c.PgQuery__JsonTablePathSpec,
    JsonTableSiblingJoin: *const c.PgQuery__JsonTableSiblingJoin,
    JsonValueExpr: *const c.PgQuery__JsonValueExpr,
    List: *const c.PgQuery__List,
    ListenStmt: *const c.PgQuery__ListenStmt,
    LoadStmt: *const c.PgQuery__LoadStmt,
    LockStmt: *const c.PgQuery__LockStmt,
    LockingClause: *const c.PgQuery__LockingClause,
    MergeAction: *const c.PgQuery__MergeAction,
    MergeStmt: *const c.PgQuery__MergeStmt,
    MergeSupportFunc: *const c.PgQuery__MergeSupportFunc,
    MergeWhenClause: *const c.PgQuery__MergeWhenClause,
    MinMaxExpr: *const c.PgQuery__MinMaxExpr,
    MultiAssignRef: *const c.PgQuery__MultiAssignRef,
    NamedArgExpr: *const c.PgQuery__NamedArgExpr,
    NextValueExpr: *const c.PgQuery__NextValueExpr,
    NotifyStmt: *const c.PgQuery__NotifyStmt,
    NullIfExpr: *const c.PgQuery__NullIfExpr,
    NullTest: *const c.PgQuery__NullTest,
    ObjectWithArgs: *const c.PgQuery__ObjectWithArgs,
    OidList: *const c.PgQuery__OidList,
    OnConflictClause: *const c.PgQuery__OnConflictClause,
    OnConflictExpr: *const c.PgQuery__OnConflictExpr,
    OpExpr: *const c.PgQuery__OpExpr,
    Param: *const c.PgQuery__Param,
    ParamRef: *const c.PgQuery__ParamRef,
    PartitionBoundSpec: *const c.PgQuery__PartitionBoundSpec,
    PartitionCmd: *const c.PgQuery__PartitionCmd,
    PartitionElem: *const c.PgQuery__PartitionElem,
    PartitionRangeDatum: *const c.PgQuery__PartitionRangeDatum,
    PartitionSpec: *const c.PgQuery__PartitionSpec,
    PlassignStmt: *const c.PgQuery__PLAssignStmt,
    PrepareStmt: *const c.PgQuery__PrepareStmt,
    PublicationObjSpec: *const c.PgQuery__PublicationObjSpec,
    PublicationTable: *const c.PgQuery__PublicationTable,
    Query: *const c.PgQuery__Query,
    RangeFunction: *const c.PgQuery__RangeFunction,
    RangeSubselect: *const c.PgQuery__RangeSubselect,
    RangeTableFunc: *const c.PgQuery__RangeTableFunc,
    RangeTableFuncCol: *const c.PgQuery__RangeTableFuncCol,
    RangeTableSample: *const c.PgQuery__RangeTableSample,
    RangeTblEntry: *const c.PgQuery__RangeTblEntry,
    RangeTblFunction: *const c.PgQuery__RangeTblFunction,
    RangeTblRef: *const c.PgQuery__RangeTblRef,
    RangeVar: *const c.PgQuery__RangeVar,
    RawStmt: *const c.PgQuery__RawStmt,
    ReassignOwnedStmt: *const c.PgQuery__ReassignOwnedStmt,
    RefreshMatViewStmt: *const c.PgQuery__RefreshMatViewStmt,
    ReindexStmt: *const c.PgQuery__ReindexStmt,
    RelabelType: *const c.PgQuery__RelabelType,
    RenameStmt: *const c.PgQuery__RenameStmt,
    ReplicaIdentityStmt: *const c.PgQuery__ReplicaIdentityStmt,
    ResTarget: *const c.PgQuery__ResTarget,
    ReturnStmt: *const c.PgQuery__ReturnStmt,
    RoleSpec: *const c.PgQuery__RoleSpec,
    RowCompareExpr: *const c.PgQuery__RowCompareExpr,
    RowExpr: *const c.PgQuery__RowExpr,
    RowMarkClause: *const c.PgQuery__RowMarkClause,
    RtepermissionInfo: *const c.PgQuery__RTEPermissionInfo,
    RuleStmt: *const c.PgQuery__RuleStmt,
    ScalarArrayOpExpr: *const c.PgQuery__ScalarArrayOpExpr,
    SecLabelStmt: *const c.PgQuery__SecLabelStmt,
    SelectStmt: *const c.PgQuery__SelectStmt,
    SetOperationStmt: *const c.PgQuery__SetOperationStmt,
    SetToDefault: *const c.PgQuery__SetToDefault,
    SinglePartitionSpec: *const c.PgQuery__SinglePartitionSpec,
    SortBy: *const c.PgQuery__SortBy,
    SortGroupClause: *const c.PgQuery__SortGroupClause,
    SqlvalueFunction: *const c.PgQuery__SQLValueFunction,
    StatsElem: *const c.PgQuery__StatsElem,
    String: *const c.PgQuery__String,
    SubLink: *const c.PgQuery__SubLink,
    SubPlan: *const c.PgQuery__SubPlan,
    SubscriptingRef: *const c.PgQuery__SubscriptingRef,
    TableFunc: *const c.PgQuery__TableFunc,
    TableLikeClause: *const c.PgQuery__TableLikeClause,
    TableSampleClause: *const c.PgQuery__TableSampleClause,
    TargetEntry: *const c.PgQuery__TargetEntry,
    TransactionStmt: *const c.PgQuery__TransactionStmt,
    TriggerTransition: *const c.PgQuery__TriggerTransition,
    TruncateStmt: *const c.PgQuery__TruncateStmt,
    TypeCast: *const c.PgQuery__TypeCast,
    TypeName: *const c.PgQuery__TypeName,
    UnlistenStmt: *const c.PgQuery__UnlistenStmt,
    UpdateStmt: *const c.PgQuery__UpdateStmt,
    VacuumRelation: *const c.PgQuery__VacuumRelation,
    VacuumStmt: *const c.PgQuery__VacuumStmt,
    Var: *const c.PgQuery__Var,
    VariableSetStmt: *const c.PgQuery__VariableSetStmt,
    VariableShowStmt: *const c.PgQuery__VariableShowStmt,
    ViewStmt: *const c.PgQuery__ViewStmt,
    WindowClause: *const c.PgQuery__WindowClause,
    WindowDef: *const c.PgQuery__WindowDef,
    WindowFunc: *const c.PgQuery__WindowFunc,
    WindowFuncRunCondition: *const c.PgQuery__WindowFuncRunCondition,
    WithCheckOption: *const c.PgQuery__WithCheckOption,
    WithClause: *const c.PgQuery__WithClause,
    XmlExpr: *const c.PgQuery__XmlExpr,
    XmlSerialize: *const c.PgQuery__XmlSerialize,

    pub fn deparse(self: NodeRef, allocator: root.Allocator) root.ApiError!root.Outcome(root.OwnedString) {
        return root.ops.deparseNodeRef(allocator, self);
    }
};

pub fn toRef(node: *const c.PgQuery__Node) ?NodeRef {
    return switch (node.node_case) {
        c.PG_QUERY__NODE__NODE_A_ARRAY_EXPR => .{ .AArrayExpr = node.unnamed_0.a_array_expr },
        c.PG_QUERY__NODE__NODE_A_CONST => .{ .AConst = node.unnamed_0.a_const },
        c.PG_QUERY__NODE__NODE_A_EXPR => .{ .AExpr = node.unnamed_0.a_expr },
        c.PG_QUERY__NODE__NODE_A_INDICES => .{ .AIndices = node.unnamed_0.a_indices },
        c.PG_QUERY__NODE__NODE_A_INDIRECTION => .{ .AIndirection = node.unnamed_0.a_indirection },
        c.PG_QUERY__NODE__NODE_A_STAR => .{ .AStar = node.unnamed_0.a_star },
        c.PG_QUERY__NODE__NODE_ACCESS_PRIV => .{ .AccessPriv = node.unnamed_0.access_priv },
        c.PG_QUERY__NODE__NODE_AGGREF => .{ .Aggref = node.unnamed_0.aggref },
        c.PG_QUERY__NODE__NODE_ALIAS => .{ .Alias = node.unnamed_0.alias },
        c.PG_QUERY__NODE__NODE_ALTER_COLLATION_STMT => .{ .AlterCollationStmt = node.unnamed_0.alter_collation_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_DATABASE_REFRESH_COLL_STMT => .{ .AlterDatabaseRefreshCollStmt = node.unnamed_0.alter_database_refresh_coll_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_DATABASE_SET_STMT => .{ .AlterDatabaseSetStmt = node.unnamed_0.alter_database_set_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_DATABASE_STMT => .{ .AlterDatabaseStmt = node.unnamed_0.alter_database_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_DEFAULT_PRIVILEGES_STMT => .{ .AlterDefaultPrivilegesStmt = node.unnamed_0.alter_default_privileges_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_DOMAIN_STMT => .{ .AlterDomainStmt = node.unnamed_0.alter_domain_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_ENUM_STMT => .{ .AlterEnumStmt = node.unnamed_0.alter_enum_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_EVENT_TRIG_STMT => .{ .AlterEventTrigStmt = node.unnamed_0.alter_event_trig_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_EXTENSION_CONTENTS_STMT => .{ .AlterExtensionContentsStmt = node.unnamed_0.alter_extension_contents_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_EXTENSION_STMT => .{ .AlterExtensionStmt = node.unnamed_0.alter_extension_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_FDW_STMT => .{ .AlterFdwStmt = node.unnamed_0.alter_fdw_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_FOREIGN_SERVER_STMT => .{ .AlterForeignServerStmt = node.unnamed_0.alter_foreign_server_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_FUNCTION_STMT => .{ .AlterFunctionStmt = node.unnamed_0.alter_function_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_OBJECT_DEPENDS_STMT => .{ .AlterObjectDependsStmt = node.unnamed_0.alter_object_depends_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_OBJECT_SCHEMA_STMT => .{ .AlterObjectSchemaStmt = node.unnamed_0.alter_object_schema_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_OP_FAMILY_STMT => .{ .AlterOpFamilyStmt = node.unnamed_0.alter_op_family_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_OPERATOR_STMT => .{ .AlterOperatorStmt = node.unnamed_0.alter_operator_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_OWNER_STMT => .{ .AlterOwnerStmt = node.unnamed_0.alter_owner_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_POLICY_STMT => .{ .AlterPolicyStmt = node.unnamed_0.alter_policy_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_PUBLICATION_STMT => .{ .AlterPublicationStmt = node.unnamed_0.alter_publication_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_ROLE_SET_STMT => .{ .AlterRoleSetStmt = node.unnamed_0.alter_role_set_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_ROLE_STMT => .{ .AlterRoleStmt = node.unnamed_0.alter_role_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_SEQ_STMT => .{ .AlterSeqStmt = node.unnamed_0.alter_seq_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_STATS_STMT => .{ .AlterStatsStmt = node.unnamed_0.alter_stats_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_SUBSCRIPTION_STMT => .{ .AlterSubscriptionStmt = node.unnamed_0.alter_subscription_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_SYSTEM_STMT => .{ .AlterSystemStmt = node.unnamed_0.alter_system_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_TABLE_CMD => .{ .AlterTableCmd = node.unnamed_0.alter_table_cmd },
        c.PG_QUERY__NODE__NODE_ALTER_TABLE_MOVE_ALL_STMT => .{ .AlterTableMoveAllStmt = node.unnamed_0.alter_table_move_all_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_TABLE_SPACE_OPTIONS_STMT => .{ .AlterTableSpaceOptionsStmt = node.unnamed_0.alter_table_space_options_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_TABLE_STMT => .{ .AlterTableStmt = node.unnamed_0.alter_table_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_TSCONFIGURATION_STMT => .{ .AlterTsconfigurationStmt = node.unnamed_0.alter_tsconfiguration_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_TSDICTIONARY_STMT => .{ .AlterTsdictionaryStmt = node.unnamed_0.alter_tsdictionary_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_TYPE_STMT => .{ .AlterTypeStmt = node.unnamed_0.alter_type_stmt },
        c.PG_QUERY__NODE__NODE_ALTER_USER_MAPPING_STMT => .{ .AlterUserMappingStmt = node.unnamed_0.alter_user_mapping_stmt },
        c.PG_QUERY__NODE__NODE_ALTERNATIVE_SUB_PLAN => .{ .AlternativeSubPlan = node.unnamed_0.alternative_sub_plan },
        c.PG_QUERY__NODE__NODE_ARRAY_COERCE_EXPR => .{ .ArrayCoerceExpr = node.unnamed_0.array_coerce_expr },
        c.PG_QUERY__NODE__NODE_ARRAY_EXPR => .{ .ArrayExpr = node.unnamed_0.array_expr },
        c.PG_QUERY__NODE__NODE_BIT_STRING => .{ .BitString = node.unnamed_0.bit_string },
        c.PG_QUERY__NODE__NODE_BOOL_EXPR => .{ .BoolExpr = node.unnamed_0.bool_expr },
        c.PG_QUERY__NODE__NODE_BOOLEAN => .{ .Boolean = node.unnamed_0.boolean },
        c.PG_QUERY__NODE__NODE_BOOLEAN_TEST => .{ .BooleanTest = node.unnamed_0.boolean_test },
        c.PG_QUERY__NODE__NODE_CALL_CONTEXT => .{ .CallContext = node.unnamed_0.call_context },
        c.PG_QUERY__NODE__NODE_CALL_STMT => .{ .CallStmt = node.unnamed_0.call_stmt },
        c.PG_QUERY__NODE__NODE_CASE_EXPR => .{ .CaseExpr = node.unnamed_0.case_expr },
        c.PG_QUERY__NODE__NODE_CASE_TEST_EXPR => .{ .CaseTestExpr = node.unnamed_0.case_test_expr },
        c.PG_QUERY__NODE__NODE_CASE_WHEN => .{ .CaseWhen = node.unnamed_0.case_when },
        c.PG_QUERY__NODE__NODE_CHECK_POINT_STMT => .{ .CheckPointStmt = node.unnamed_0.check_point_stmt },
        c.PG_QUERY__NODE__NODE_CLOSE_PORTAL_STMT => .{ .ClosePortalStmt = node.unnamed_0.close_portal_stmt },
        c.PG_QUERY__NODE__NODE_CLUSTER_STMT => .{ .ClusterStmt = node.unnamed_0.cluster_stmt },
        c.PG_QUERY__NODE__NODE_COALESCE_EXPR => .{ .CoalesceExpr = node.unnamed_0.coalesce_expr },
        c.PG_QUERY__NODE__NODE_COERCE_TO_DOMAIN => .{ .CoerceToDomain = node.unnamed_0.coerce_to_domain },
        c.PG_QUERY__NODE__NODE_COERCE_TO_DOMAIN_VALUE => .{ .CoerceToDomainValue = node.unnamed_0.coerce_to_domain_value },
        c.PG_QUERY__NODE__NODE_COERCE_VIA_IO => .{ .CoerceViaIo = node.unnamed_0.coerce_via_io },
        c.PG_QUERY__NODE__NODE_COLLATE_CLAUSE => .{ .CollateClause = node.unnamed_0.collate_clause },
        c.PG_QUERY__NODE__NODE_COLLATE_EXPR => .{ .CollateExpr = node.unnamed_0.collate_expr },
        c.PG_QUERY__NODE__NODE_COLUMN_DEF => .{ .ColumnDef = node.unnamed_0.column_def },
        c.PG_QUERY__NODE__NODE_COLUMN_REF => .{ .ColumnRef = node.unnamed_0.column_ref },
        c.PG_QUERY__NODE__NODE_COMMENT_STMT => .{ .CommentStmt = node.unnamed_0.comment_stmt },
        c.PG_QUERY__NODE__NODE_COMMON_TABLE_EXPR => .{ .CommonTableExpr = node.unnamed_0.common_table_expr },
        c.PG_QUERY__NODE__NODE_COMPOSITE_TYPE_STMT => .{ .CompositeTypeStmt = node.unnamed_0.composite_type_stmt },
        c.PG_QUERY__NODE__NODE_CONSTRAINT => .{ .Constraint = node.unnamed_0.constraint },
        c.PG_QUERY__NODE__NODE_CONSTRAINTS_SET_STMT => .{ .ConstraintsSetStmt = node.unnamed_0.constraints_set_stmt },
        c.PG_QUERY__NODE__NODE_CONVERT_ROWTYPE_EXPR => .{ .ConvertRowtypeExpr = node.unnamed_0.convert_rowtype_expr },
        c.PG_QUERY__NODE__NODE_COPY_STMT => .{ .CopyStmt = node.unnamed_0.copy_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_AM_STMT => .{ .CreateAmStmt = node.unnamed_0.create_am_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_CAST_STMT => .{ .CreateCastStmt = node.unnamed_0.create_cast_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_CONVERSION_STMT => .{ .CreateConversionStmt = node.unnamed_0.create_conversion_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_DOMAIN_STMT => .{ .CreateDomainStmt = node.unnamed_0.create_domain_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_ENUM_STMT => .{ .CreateEnumStmt = node.unnamed_0.create_enum_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_EVENT_TRIG_STMT => .{ .CreateEventTrigStmt = node.unnamed_0.create_event_trig_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_EXTENSION_STMT => .{ .CreateExtensionStmt = node.unnamed_0.create_extension_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_FDW_STMT => .{ .CreateFdwStmt = node.unnamed_0.create_fdw_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_FOREIGN_SERVER_STMT => .{ .CreateForeignServerStmt = node.unnamed_0.create_foreign_server_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_FOREIGN_TABLE_STMT => .{ .CreateForeignTableStmt = node.unnamed_0.create_foreign_table_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_FUNCTION_STMT => .{ .CreateFunctionStmt = node.unnamed_0.create_function_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_OP_CLASS_ITEM => .{ .CreateOpClassItem = node.unnamed_0.create_op_class_item },
        c.PG_QUERY__NODE__NODE_CREATE_OP_CLASS_STMT => .{ .CreateOpClassStmt = node.unnamed_0.create_op_class_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_OP_FAMILY_STMT => .{ .CreateOpFamilyStmt = node.unnamed_0.create_op_family_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_PLANG_STMT => .{ .CreatePlangStmt = node.unnamed_0.create_plang_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_POLICY_STMT => .{ .CreatePolicyStmt = node.unnamed_0.create_policy_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_PUBLICATION_STMT => .{ .CreatePublicationStmt = node.unnamed_0.create_publication_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_RANGE_STMT => .{ .CreateRangeStmt = node.unnamed_0.create_range_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_ROLE_STMT => .{ .CreateRoleStmt = node.unnamed_0.create_role_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_SCHEMA_STMT => .{ .CreateSchemaStmt = node.unnamed_0.create_schema_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_SEQ_STMT => .{ .CreateSeqStmt = node.unnamed_0.create_seq_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_STATS_STMT => .{ .CreateStatsStmt = node.unnamed_0.create_stats_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_STMT => .{ .CreateStmt = node.unnamed_0.create_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_SUBSCRIPTION_STMT => .{ .CreateSubscriptionStmt = node.unnamed_0.create_subscription_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_TABLE_AS_STMT => .{ .CreateTableAsStmt = node.unnamed_0.create_table_as_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_TABLE_SPACE_STMT => .{ .CreateTableSpaceStmt = node.unnamed_0.create_table_space_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_TRANSFORM_STMT => .{ .CreateTransformStmt = node.unnamed_0.create_transform_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_TRIG_STMT => .{ .CreateTrigStmt = node.unnamed_0.create_trig_stmt },
        c.PG_QUERY__NODE__NODE_CREATE_USER_MAPPING_STMT => .{ .CreateUserMappingStmt = node.unnamed_0.create_user_mapping_stmt },
        c.PG_QUERY__NODE__NODE_CREATEDB_STMT => .{ .CreatedbStmt = node.unnamed_0.createdb_stmt },
        c.PG_QUERY__NODE__NODE_CTECYCLE_CLAUSE => .{ .CtecycleClause = node.unnamed_0.ctecycle_clause },
        c.PG_QUERY__NODE__NODE_CTESEARCH_CLAUSE => .{ .CtesearchClause = node.unnamed_0.ctesearch_clause },
        c.PG_QUERY__NODE__NODE_CURRENT_OF_EXPR => .{ .CurrentOfExpr = node.unnamed_0.current_of_expr },
        c.PG_QUERY__NODE__NODE_DEALLOCATE_STMT => .{ .DeallocateStmt = node.unnamed_0.deallocate_stmt },
        c.PG_QUERY__NODE__NODE_DECLARE_CURSOR_STMT => .{ .DeclareCursorStmt = node.unnamed_0.declare_cursor_stmt },
        c.PG_QUERY__NODE__NODE_DEF_ELEM => .{ .DefElem = node.unnamed_0.def_elem },
        c.PG_QUERY__NODE__NODE_DEFINE_STMT => .{ .DefineStmt = node.unnamed_0.define_stmt },
        c.PG_QUERY__NODE__NODE_DELETE_STMT => .{ .DeleteStmt = node.unnamed_0.delete_stmt },
        c.PG_QUERY__NODE__NODE_DISCARD_STMT => .{ .DiscardStmt = node.unnamed_0.discard_stmt },
        c.PG_QUERY__NODE__NODE_DISTINCT_EXPR => .{ .DistinctExpr = node.unnamed_0.distinct_expr },
        c.PG_QUERY__NODE__NODE_DO_STMT => .{ .DoStmt = node.unnamed_0.do_stmt },
        c.PG_QUERY__NODE__NODE_DROP_OWNED_STMT => .{ .DropOwnedStmt = node.unnamed_0.drop_owned_stmt },
        c.PG_QUERY__NODE__NODE_DROP_ROLE_STMT => .{ .DropRoleStmt = node.unnamed_0.drop_role_stmt },
        c.PG_QUERY__NODE__NODE_DROP_STMT => .{ .DropStmt = node.unnamed_0.drop_stmt },
        c.PG_QUERY__NODE__NODE_DROP_SUBSCRIPTION_STMT => .{ .DropSubscriptionStmt = node.unnamed_0.drop_subscription_stmt },
        c.PG_QUERY__NODE__NODE_DROP_TABLE_SPACE_STMT => .{ .DropTableSpaceStmt = node.unnamed_0.drop_table_space_stmt },
        c.PG_QUERY__NODE__NODE_DROP_USER_MAPPING_STMT => .{ .DropUserMappingStmt = node.unnamed_0.drop_user_mapping_stmt },
        c.PG_QUERY__NODE__NODE_DROPDB_STMT => .{ .DropdbStmt = node.unnamed_0.dropdb_stmt },
        c.PG_QUERY__NODE__NODE_EXECUTE_STMT => .{ .ExecuteStmt = node.unnamed_0.execute_stmt },
        c.PG_QUERY__NODE__NODE_EXPLAIN_STMT => .{ .ExplainStmt = node.unnamed_0.explain_stmt },
        c.PG_QUERY__NODE__NODE_FETCH_STMT => .{ .FetchStmt = node.unnamed_0.fetch_stmt },
        c.PG_QUERY__NODE__NODE_FIELD_SELECT => .{ .FieldSelect = node.unnamed_0.field_select },
        c.PG_QUERY__NODE__NODE_FIELD_STORE => .{ .FieldStore = node.unnamed_0.field_store },
        c.PG_QUERY__NODE__NODE_FLOAT => .{ .Float = node.unnamed_0.float_ },
        c.PG_QUERY__NODE__NODE_FROM_EXPR => .{ .FromExpr = node.unnamed_0.from_expr },
        c.PG_QUERY__NODE__NODE_FUNC_CALL => .{ .FuncCall = node.unnamed_0.func_call },
        c.PG_QUERY__NODE__NODE_FUNC_EXPR => .{ .FuncExpr = node.unnamed_0.func_expr },
        c.PG_QUERY__NODE__NODE_FUNCTION_PARAMETER => .{ .FunctionParameter = node.unnamed_0.function_parameter },
        c.PG_QUERY__NODE__NODE_GRANT_ROLE_STMT => .{ .GrantRoleStmt = node.unnamed_0.grant_role_stmt },
        c.PG_QUERY__NODE__NODE_GRANT_STMT => .{ .GrantStmt = node.unnamed_0.grant_stmt },
        c.PG_QUERY__NODE__NODE_GROUPING_FUNC => .{ .GroupingFunc = node.unnamed_0.grouping_func },
        c.PG_QUERY__NODE__NODE_GROUPING_SET => .{ .GroupingSet = node.unnamed_0.grouping_set },
        c.PG_QUERY__NODE__NODE_IMPORT_FOREIGN_SCHEMA_STMT => .{ .ImportForeignSchemaStmt = node.unnamed_0.import_foreign_schema_stmt },
        c.PG_QUERY__NODE__NODE_INDEX_ELEM => .{ .IndexElem = node.unnamed_0.index_elem },
        c.PG_QUERY__NODE__NODE_INDEX_STMT => .{ .IndexStmt = node.unnamed_0.index_stmt },
        c.PG_QUERY__NODE__NODE_INFER_CLAUSE => .{ .InferClause = node.unnamed_0.infer_clause },
        c.PG_QUERY__NODE__NODE_INFERENCE_ELEM => .{ .InferenceElem = node.unnamed_0.inference_elem },
        c.PG_QUERY__NODE__NODE_INLINE_CODE_BLOCK => .{ .InlineCodeBlock = node.unnamed_0.inline_code_block },
        c.PG_QUERY__NODE__NODE_INSERT_STMT => .{ .InsertStmt = node.unnamed_0.insert_stmt },
        c.PG_QUERY__NODE__NODE_INT_LIST => .{ .IntList = node.unnamed_0.int_list },
        c.PG_QUERY__NODE__NODE_INTEGER => .{ .Integer = node.unnamed_0.integer },
        c.PG_QUERY__NODE__NODE_INTO_CLAUSE => .{ .IntoClause = node.unnamed_0.into_clause },
        c.PG_QUERY__NODE__NODE_JOIN_EXPR => .{ .JoinExpr = node.unnamed_0.join_expr },
        c.PG_QUERY__NODE__NODE_JSON_AGG_CONSTRUCTOR => .{ .JsonAggConstructor = node.unnamed_0.json_agg_constructor },
        c.PG_QUERY__NODE__NODE_JSON_ARGUMENT => .{ .JsonArgument = node.unnamed_0.json_argument },
        c.PG_QUERY__NODE__NODE_JSON_ARRAY_AGG => .{ .JsonArrayAgg = node.unnamed_0.json_array_agg },
        c.PG_QUERY__NODE__NODE_JSON_ARRAY_CONSTRUCTOR => .{ .JsonArrayConstructor = node.unnamed_0.json_array_constructor },
        c.PG_QUERY__NODE__NODE_JSON_ARRAY_QUERY_CONSTRUCTOR => .{ .JsonArrayQueryConstructor = node.unnamed_0.json_array_query_constructor },
        c.PG_QUERY__NODE__NODE_JSON_BEHAVIOR => .{ .JsonBehavior = node.unnamed_0.json_behavior },
        c.PG_QUERY__NODE__NODE_JSON_CONSTRUCTOR_EXPR => .{ .JsonConstructorExpr = node.unnamed_0.json_constructor_expr },
        c.PG_QUERY__NODE__NODE_JSON_EXPR => .{ .JsonExpr = node.unnamed_0.json_expr },
        c.PG_QUERY__NODE__NODE_JSON_FORMAT => .{ .JsonFormat = node.unnamed_0.json_format },
        c.PG_QUERY__NODE__NODE_JSON_FUNC_EXPR => .{ .JsonFuncExpr = node.unnamed_0.json_func_expr },
        c.PG_QUERY__NODE__NODE_JSON_IS_PREDICATE => .{ .JsonIsPredicate = node.unnamed_0.json_is_predicate },
        c.PG_QUERY__NODE__NODE_JSON_KEY_VALUE => .{ .JsonKeyValue = node.unnamed_0.json_key_value },
        c.PG_QUERY__NODE__NODE_JSON_OBJECT_AGG => .{ .JsonObjectAgg = node.unnamed_0.json_object_agg },
        c.PG_QUERY__NODE__NODE_JSON_OBJECT_CONSTRUCTOR => .{ .JsonObjectConstructor = node.unnamed_0.json_object_constructor },
        c.PG_QUERY__NODE__NODE_JSON_OUTPUT => .{ .JsonOutput = node.unnamed_0.json_output },
        c.PG_QUERY__NODE__NODE_JSON_PARSE_EXPR => .{ .JsonParseExpr = node.unnamed_0.json_parse_expr },
        c.PG_QUERY__NODE__NODE_JSON_RETURNING => .{ .JsonReturning = node.unnamed_0.json_returning },
        c.PG_QUERY__NODE__NODE_JSON_SCALAR_EXPR => .{ .JsonScalarExpr = node.unnamed_0.json_scalar_expr },
        c.PG_QUERY__NODE__NODE_JSON_SERIALIZE_EXPR => .{ .JsonSerializeExpr = node.unnamed_0.json_serialize_expr },
        c.PG_QUERY__NODE__NODE_JSON_TABLE => .{ .JsonTable = node.unnamed_0.json_table },
        c.PG_QUERY__NODE__NODE_JSON_TABLE_COLUMN => .{ .JsonTableColumn = node.unnamed_0.json_table_column },
        c.PG_QUERY__NODE__NODE_JSON_TABLE_PATH => .{ .JsonTablePath = node.unnamed_0.json_table_path },
        c.PG_QUERY__NODE__NODE_JSON_TABLE_PATH_SCAN => .{ .JsonTablePathScan = node.unnamed_0.json_table_path_scan },
        c.PG_QUERY__NODE__NODE_JSON_TABLE_PATH_SPEC => .{ .JsonTablePathSpec = node.unnamed_0.json_table_path_spec },
        c.PG_QUERY__NODE__NODE_JSON_TABLE_SIBLING_JOIN => .{ .JsonTableSiblingJoin = node.unnamed_0.json_table_sibling_join },
        c.PG_QUERY__NODE__NODE_JSON_VALUE_EXPR => .{ .JsonValueExpr = node.unnamed_0.json_value_expr },
        c.PG_QUERY__NODE__NODE_LIST => .{ .List = node.unnamed_0.list },
        c.PG_QUERY__NODE__NODE_LISTEN_STMT => .{ .ListenStmt = node.unnamed_0.listen_stmt },
        c.PG_QUERY__NODE__NODE_LOAD_STMT => .{ .LoadStmt = node.unnamed_0.load_stmt },
        c.PG_QUERY__NODE__NODE_LOCK_STMT => .{ .LockStmt = node.unnamed_0.lock_stmt },
        c.PG_QUERY__NODE__NODE_LOCKING_CLAUSE => .{ .LockingClause = node.unnamed_0.locking_clause },
        c.PG_QUERY__NODE__NODE_MERGE_ACTION => .{ .MergeAction = node.unnamed_0.merge_action },
        c.PG_QUERY__NODE__NODE_MERGE_STMT => .{ .MergeStmt = node.unnamed_0.merge_stmt },
        c.PG_QUERY__NODE__NODE_MERGE_SUPPORT_FUNC => .{ .MergeSupportFunc = node.unnamed_0.merge_support_func },
        c.PG_QUERY__NODE__NODE_MERGE_WHEN_CLAUSE => .{ .MergeWhenClause = node.unnamed_0.merge_when_clause },
        c.PG_QUERY__NODE__NODE_MIN_MAX_EXPR => .{ .MinMaxExpr = node.unnamed_0.min_max_expr },
        c.PG_QUERY__NODE__NODE_MULTI_ASSIGN_REF => .{ .MultiAssignRef = node.unnamed_0.multi_assign_ref },
        c.PG_QUERY__NODE__NODE_NAMED_ARG_EXPR => .{ .NamedArgExpr = node.unnamed_0.named_arg_expr },
        c.PG_QUERY__NODE__NODE_NEXT_VALUE_EXPR => .{ .NextValueExpr = node.unnamed_0.next_value_expr },
        c.PG_QUERY__NODE__NODE_NOTIFY_STMT => .{ .NotifyStmt = node.unnamed_0.notify_stmt },
        c.PG_QUERY__NODE__NODE_NULL_IF_EXPR => .{ .NullIfExpr = node.unnamed_0.null_if_expr },
        c.PG_QUERY__NODE__NODE_NULL_TEST => .{ .NullTest = node.unnamed_0.null_test },
        c.PG_QUERY__NODE__NODE_OBJECT_WITH_ARGS => .{ .ObjectWithArgs = node.unnamed_0.object_with_args },
        c.PG_QUERY__NODE__NODE_OID_LIST => .{ .OidList = node.unnamed_0.oid_list },
        c.PG_QUERY__NODE__NODE_ON_CONFLICT_CLAUSE => .{ .OnConflictClause = node.unnamed_0.on_conflict_clause },
        c.PG_QUERY__NODE__NODE_ON_CONFLICT_EXPR => .{ .OnConflictExpr = node.unnamed_0.on_conflict_expr },
        c.PG_QUERY__NODE__NODE_OP_EXPR => .{ .OpExpr = node.unnamed_0.op_expr },
        c.PG_QUERY__NODE__NODE_PARAM => .{ .Param = node.unnamed_0.param },
        c.PG_QUERY__NODE__NODE_PARAM_REF => .{ .ParamRef = node.unnamed_0.param_ref },
        c.PG_QUERY__NODE__NODE_PARTITION_BOUND_SPEC => .{ .PartitionBoundSpec = node.unnamed_0.partition_bound_spec },
        c.PG_QUERY__NODE__NODE_PARTITION_CMD => .{ .PartitionCmd = node.unnamed_0.partition_cmd },
        c.PG_QUERY__NODE__NODE_PARTITION_ELEM => .{ .PartitionElem = node.unnamed_0.partition_elem },
        c.PG_QUERY__NODE__NODE_PARTITION_RANGE_DATUM => .{ .PartitionRangeDatum = node.unnamed_0.partition_range_datum },
        c.PG_QUERY__NODE__NODE_PARTITION_SPEC => .{ .PartitionSpec = node.unnamed_0.partition_spec },
        c.PG_QUERY__NODE__NODE_PLASSIGN_STMT => .{ .PlassignStmt = node.unnamed_0.plassign_stmt },
        c.PG_QUERY__NODE__NODE_PREPARE_STMT => .{ .PrepareStmt = node.unnamed_0.prepare_stmt },
        c.PG_QUERY__NODE__NODE_PUBLICATION_OBJ_SPEC => .{ .PublicationObjSpec = node.unnamed_0.publication_obj_spec },
        c.PG_QUERY__NODE__NODE_PUBLICATION_TABLE => .{ .PublicationTable = node.unnamed_0.publication_table },
        c.PG_QUERY__NODE__NODE_QUERY => .{ .Query = node.unnamed_0.query },
        c.PG_QUERY__NODE__NODE_RANGE_FUNCTION => .{ .RangeFunction = node.unnamed_0.range_function },
        c.PG_QUERY__NODE__NODE_RANGE_SUBSELECT => .{ .RangeSubselect = node.unnamed_0.range_subselect },
        c.PG_QUERY__NODE__NODE_RANGE_TABLE_FUNC => .{ .RangeTableFunc = node.unnamed_0.range_table_func },
        c.PG_QUERY__NODE__NODE_RANGE_TABLE_FUNC_COL => .{ .RangeTableFuncCol = node.unnamed_0.range_table_func_col },
        c.PG_QUERY__NODE__NODE_RANGE_TABLE_SAMPLE => .{ .RangeTableSample = node.unnamed_0.range_table_sample },
        c.PG_QUERY__NODE__NODE_RANGE_TBL_ENTRY => .{ .RangeTblEntry = node.unnamed_0.range_tbl_entry },
        c.PG_QUERY__NODE__NODE_RANGE_TBL_FUNCTION => .{ .RangeTblFunction = node.unnamed_0.range_tbl_function },
        c.PG_QUERY__NODE__NODE_RANGE_TBL_REF => .{ .RangeTblRef = node.unnamed_0.range_tbl_ref },
        c.PG_QUERY__NODE__NODE_RANGE_VAR => .{ .RangeVar = node.unnamed_0.range_var },
        c.PG_QUERY__NODE__NODE_RAW_STMT => .{ .RawStmt = node.unnamed_0.raw_stmt },
        c.PG_QUERY__NODE__NODE_REASSIGN_OWNED_STMT => .{ .ReassignOwnedStmt = node.unnamed_0.reassign_owned_stmt },
        c.PG_QUERY__NODE__NODE_REFRESH_MAT_VIEW_STMT => .{ .RefreshMatViewStmt = node.unnamed_0.refresh_mat_view_stmt },
        c.PG_QUERY__NODE__NODE_REINDEX_STMT => .{ .ReindexStmt = node.unnamed_0.reindex_stmt },
        c.PG_QUERY__NODE__NODE_RELABEL_TYPE => .{ .RelabelType = node.unnamed_0.relabel_type },
        c.PG_QUERY__NODE__NODE_RENAME_STMT => .{ .RenameStmt = node.unnamed_0.rename_stmt },
        c.PG_QUERY__NODE__NODE_REPLICA_IDENTITY_STMT => .{ .ReplicaIdentityStmt = node.unnamed_0.replica_identity_stmt },
        c.PG_QUERY__NODE__NODE_RES_TARGET => .{ .ResTarget = node.unnamed_0.res_target },
        c.PG_QUERY__NODE__NODE_RETURN_STMT => .{ .ReturnStmt = node.unnamed_0.return_stmt },
        c.PG_QUERY__NODE__NODE_ROLE_SPEC => .{ .RoleSpec = node.unnamed_0.role_spec },
        c.PG_QUERY__NODE__NODE_ROW_COMPARE_EXPR => .{ .RowCompareExpr = node.unnamed_0.row_compare_expr },
        c.PG_QUERY__NODE__NODE_ROW_EXPR => .{ .RowExpr = node.unnamed_0.row_expr },
        c.PG_QUERY__NODE__NODE_ROW_MARK_CLAUSE => .{ .RowMarkClause = node.unnamed_0.row_mark_clause },
        c.PG_QUERY__NODE__NODE_RTEPERMISSION_INFO => .{ .RtepermissionInfo = node.unnamed_0.rtepermission_info },
        c.PG_QUERY__NODE__NODE_RULE_STMT => .{ .RuleStmt = node.unnamed_0.rule_stmt },
        c.PG_QUERY__NODE__NODE_SCALAR_ARRAY_OP_EXPR => .{ .ScalarArrayOpExpr = node.unnamed_0.scalar_array_op_expr },
        c.PG_QUERY__NODE__NODE_SEC_LABEL_STMT => .{ .SecLabelStmt = node.unnamed_0.sec_label_stmt },
        c.PG_QUERY__NODE__NODE_SELECT_STMT => .{ .SelectStmt = node.unnamed_0.select_stmt },
        c.PG_QUERY__NODE__NODE_SET_OPERATION_STMT => .{ .SetOperationStmt = node.unnamed_0.set_operation_stmt },
        c.PG_QUERY__NODE__NODE_SET_TO_DEFAULT => .{ .SetToDefault = node.unnamed_0.set_to_default },
        c.PG_QUERY__NODE__NODE_SINGLE_PARTITION_SPEC => .{ .SinglePartitionSpec = node.unnamed_0.single_partition_spec },
        c.PG_QUERY__NODE__NODE_SORT_BY => .{ .SortBy = node.unnamed_0.sort_by },
        c.PG_QUERY__NODE__NODE_SORT_GROUP_CLAUSE => .{ .SortGroupClause = node.unnamed_0.sort_group_clause },
        c.PG_QUERY__NODE__NODE_SQLVALUE_FUNCTION => .{ .SqlvalueFunction = node.unnamed_0.sqlvalue_function },
        c.PG_QUERY__NODE__NODE_STATS_ELEM => .{ .StatsElem = node.unnamed_0.stats_elem },
        c.PG_QUERY__NODE__NODE_STRING => .{ .String = node.unnamed_0.string },
        c.PG_QUERY__NODE__NODE_SUB_LINK => .{ .SubLink = node.unnamed_0.sub_link },
        c.PG_QUERY__NODE__NODE_SUB_PLAN => .{ .SubPlan = node.unnamed_0.sub_plan },
        c.PG_QUERY__NODE__NODE_SUBSCRIPTING_REF => .{ .SubscriptingRef = node.unnamed_0.subscripting_ref },
        c.PG_QUERY__NODE__NODE_TABLE_FUNC => .{ .TableFunc = node.unnamed_0.table_func },
        c.PG_QUERY__NODE__NODE_TABLE_LIKE_CLAUSE => .{ .TableLikeClause = node.unnamed_0.table_like_clause },
        c.PG_QUERY__NODE__NODE_TABLE_SAMPLE_CLAUSE => .{ .TableSampleClause = node.unnamed_0.table_sample_clause },
        c.PG_QUERY__NODE__NODE_TARGET_ENTRY => .{ .TargetEntry = node.unnamed_0.target_entry },
        c.PG_QUERY__NODE__NODE_TRANSACTION_STMT => .{ .TransactionStmt = node.unnamed_0.transaction_stmt },
        c.PG_QUERY__NODE__NODE_TRIGGER_TRANSITION => .{ .TriggerTransition = node.unnamed_0.trigger_transition },
        c.PG_QUERY__NODE__NODE_TRUNCATE_STMT => .{ .TruncateStmt = node.unnamed_0.truncate_stmt },
        c.PG_QUERY__NODE__NODE_TYPE_CAST => .{ .TypeCast = node.unnamed_0.type_cast },
        c.PG_QUERY__NODE__NODE_TYPE_NAME => .{ .TypeName = node.unnamed_0.type_name },
        c.PG_QUERY__NODE__NODE_UNLISTEN_STMT => .{ .UnlistenStmt = node.unnamed_0.unlisten_stmt },
        c.PG_QUERY__NODE__NODE_UPDATE_STMT => .{ .UpdateStmt = node.unnamed_0.update_stmt },
        c.PG_QUERY__NODE__NODE_VACUUM_RELATION => .{ .VacuumRelation = node.unnamed_0.vacuum_relation },
        c.PG_QUERY__NODE__NODE_VACUUM_STMT => .{ .VacuumStmt = node.unnamed_0.vacuum_stmt },
        c.PG_QUERY__NODE__NODE_VAR => .{ .Var = node.unnamed_0.@"var" },
        c.PG_QUERY__NODE__NODE_VARIABLE_SET_STMT => .{ .VariableSetStmt = node.unnamed_0.variable_set_stmt },
        c.PG_QUERY__NODE__NODE_VARIABLE_SHOW_STMT => .{ .VariableShowStmt = node.unnamed_0.variable_show_stmt },
        c.PG_QUERY__NODE__NODE_VIEW_STMT => .{ .ViewStmt = node.unnamed_0.view_stmt },
        c.PG_QUERY__NODE__NODE_WINDOW_CLAUSE => .{ .WindowClause = node.unnamed_0.window_clause },
        c.PG_QUERY__NODE__NODE_WINDOW_DEF => .{ .WindowDef = node.unnamed_0.window_def },
        c.PG_QUERY__NODE__NODE_WINDOW_FUNC => .{ .WindowFunc = node.unnamed_0.window_func },
        c.PG_QUERY__NODE__NODE_WINDOW_FUNC_RUN_CONDITION => .{ .WindowFuncRunCondition = node.unnamed_0.window_func_run_condition },
        c.PG_QUERY__NODE__NODE_WITH_CHECK_OPTION => .{ .WithCheckOption = node.unnamed_0.with_check_option },
        c.PG_QUERY__NODE__NODE_WITH_CLAUSE => .{ .WithClause = node.unnamed_0.with_clause },
        c.PG_QUERY__NODE__NODE_XML_EXPR => .{ .XmlExpr = node.unnamed_0.xml_expr },
        c.PG_QUERY__NODE__NODE_XML_SERIALIZE => .{ .XmlSerialize = node.unnamed_0.xml_serialize },
        c.PG_QUERY__NODE__NODE__NOT_SET => null,
        else => null,
    };
}
